server:
  port: 8032

spring:
  application:
    name: dtm-invoke
  datasource:
    bankb:
      username: root
      password: Huawei12#$
      url: jdbc:mysql://127.0.0.1:3306/bankb?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
    banka:
      username: root
      password: Huawei12#$
      url: jdbc:mysql://127.0.0.1:3306/banka?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver

