port: 1113
APPLICATION_ID: dtm
service_description:
  name: bank-b
  version: 1.0.1
  environment: development
servicecomb:
  monitor:
    client:
      enable: false
  release_way: canary  #新版本灰度开关
  service:
    registry:
      address: http://${cse_ip}:30100                 #本地中心
      instance:
        watch: false
        pull:
          interval: 1
  rest:
    address: 0.0.0.0:${port} #"[::]:1111?sslEnabled=false"
  handler:
    chain:
      Consumer:
        default: loadbalance,bizkeeper-consumer,dtm-consumer
      Provider:
        default: dtm-provider
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    bankb:
      username: ${db_user_name}
      password: ${db_user_pwd}
      url: jdbc:mysql://${db_ip}:3306/bankb?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver