port: 1111
APPLICATION_ID: dtm
service_description:
  name: client
  version: 1.0.1
  environment: development
servicecomb:
  monitor:
    client:
      enable: false
  release_way: canary  #新版本灰度开关
  service:
    registry:
      address: http://127.0.0.1:30100                 #本地中心
      instance:
        watch: false
        pull:
          interval: 1
  rest:
    address: 0.0.0.0:${port} #"[::]:1111?sslEnabled=false"
  handler:
    chain:
      Consumer:
        default: loadbalance,bizkeeper-consumer,dtm-consumer #,tracing-consumer   # bizkeeper-consumer loadbalance perf-stats tracing-consumer sla-consumer

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    banka:
      username: root
      password: 940909
      url: jdbc:mysql://127.0.0.1:3306/banka?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
    bankb:
      username: root
      password: 940909
      url: jdbc:mysql://127.0.0.1:3306/bankb?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver